languageCode = "zh"
title = "晚晴幽草轩轩主"
baseurl = "https://aboutme.lovejade.cn/"
theme = "aerial"

[params]
  name = "晚晴幽草轩轩主"
  description = "杨轩帅，字琼璞；晚晴幽草轩轩主，天意人间舫舫主，静晴轩别苑博主，倾城之链作者。"
  about = "I am a web developer, writer, and designer currently living in shenzhen. My interests range from arts to technology. <br/>I am also interested in reading, writing, and web development. <br/> You can click the button above to visit my website."
  googleAnalytics = "UA-86109050-4"
  copyright = "nicejade"
  designerName = "晚晴幽草轩"
  designerPath = "https://www.jeffjade.com/"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""
  favicon = "favicon.ico"

[[params.social]]
  medium = "NICELINKS"
  icon = "chrome"
  link = "https://nicelinks.site?utm_source=aboutme.lovejade.cn"
  prefix = "fab"

[[params.social]]
  medium = "Arya - 在线 Markdown 编辑器"
  icon = "pied-piper"
  link = "https://markdown.lovejade.cn/?utm_source=aboutme.lovejade.cn"
  prefix = "fab"

[[params.social]]
  medium = "晚晴幽草轩"
  icon = "blogger"
  link = "https://www.jeffjade.com/?utm_source=aboutme.lovejade.cn"
  prefix = "fab"

[[params.social]]
  medium = "静轩之别苑"
  icon = "blogger-b"
  link = "https://quickapp.lovejade.cn/?utm_source=aboutme.lovejade.cn"
  prefix = "fab"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/nicejade"
  prefix = "fab"

[[params.social]]
  medium = "微博"
  icon = "weibo"
  link = "https://weibo.com/jeffjade"
  prefix = "fab"

[[params.social]]
  medium = "微信"
  icon = "weixin"
  link = "https://www.jeffjade.com/nicelinks/#大前端联盟?utm_source=aboutme.lovejade.cn"
  prefix = "fab"

[[params.social]]
  medium = "知乎"
  icon = "zhihu"
  link = "https://www.zhihu.com/people/yang-qiong-pu"
  prefix = "fab"

[[params.social]]
  medium = "DigitalOcean"
  icon = "digital-ocean"
  link = "https://m.do.co/c/046a8e6b255c"
  prefix = "fab"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/nicejadeyang"
  prefix = "fab"

[[params.social]]
  medium = "Facebook"
  icon = "facebook-f"
  link = "https://www.facebook.com/nice.jade.yang"
  prefix = "fab"

[[params.social]]
  medium = "Instagram"
  icon = "instagram"
  link = "https://www.instagram.com/jeffjade2/"
  prefix = "fab"
